import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Maven_Pro } from "next/font/google";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import gsap from "gsap";

const MavenPro = Maven_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MavenPro.className}  antialiased fixed  w-full h-full `}
      >
        {/* <MouseFollower /> */}
        <NavBar />

        {children}
      </body>
    </html>
  );
}
gsap.registerPlugin(ScrollTrigger);
